server:
  port: 8080
# 配置git仓库地址
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      label: master  # 配置仓库的分支
      server:
        git:
          uri: https://github.com/chenhaujing/spring-cloud-config 
# 配置仓库路径
# spring.cloud.config.server.git.search-paths=myconfigpath
# 访问git仓库的用户名 spring.cloud.config.server.git.username=xxxxoooo
# 访问git仓库的用户密码 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
# spring.cloud.config.server.git.password=xxxxoooo
